name: Build and deploy spring boot app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and deploy spring app job
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setup jdk
        uses: actions/setup-java
        with:
          distribution: "corretto"
          java-version: 17

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
