name: Build and deploy spring boot app

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_DATABASE_NAME: ${{ secrets.POSTGRES_DATABASE_NAME }}
      POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DATABASE_URL: ${{ secrets.POSTGRES_DATABASE_URL }}
      SPRING_PROFILES_ACTIVE: prod

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup jdk
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: 17

      - name: Build spring application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: Dockerfile
          tags: ${{secrets.DOCKERHUB_USERNAME}}/springoauth:latest
        # run: |
        #   docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/my-image-name:latest
        #   docker push my-image-name:latest
